const Categories = [
  { value: "python", label: "Python" },
  { value: "javascript", label: "JavaScript" },
  { value: "java", label: "Java" },
  { value: "c", label: "C" },
  { value: "php", label: "PHP" },
  { value: "html", label: "HTML" },
  { value: "markdown", label: "Markdown" },
  { value: "css", label: "CSS" },
  { value: "sass", label: "Sass" },
  { value: "text", label: "Text" },
  { value: "shell", label: "Shell" },
  { value: "go", label: "Go" },
  { value: "typescript", label: "TypeScript" },
  { value: "swift", label: "Swift" },
  { value: "ruby", label: "Ruby" },
  { value: "kotlin", label: "Kotlin" },
  { value: "scala", label: "Scala" },
  { value: "rust", label: "Rust" },
  { value: "dart", label: "Dart" },
  { value: "lua", label: "Lua" },
  { value: "perl", label: "Perl" },
  { value: "r", label: "R" },
  { value: "sql", label: "SQL" },
  { value: "vb", label: "Visual Basic (VB)" },
  { value: "powershell", label: "PowerShell" },
  { value: "cobol", label: "COBOL" },
  { value: "haskell", label: "Haskell" },
  { value: "objective-c", label: "Objective-C" },
  { value: "fortran", label: "Fortran" },
  { value: "elixir", label: "Elixir" },
  { value: "pascal", label: "Pascal" },
  { value: "assembly", label: "Assembly" },
];
export default Categories;
