export const Languages = {
  en: {
    enter_the_code: "Please enter code.",
    about_title: "About D0C3+1",
    about_txt:
      "D0C3+1 is a simple but effective tool for quick code snippet creation. This application is designed with programmers and developers in mind who are looking for an easy and fast way to generate useful code for their projects.",
    about_subtitle: "Used Libraries",
    shared_links: "Shared Links",
    home: "Home",
    add_new: "Add New",
    edit: "Edit",
    about_us: "About App",
    search: "Search",
    cancel: "Cancel",
    settings: "Settings",
    view_more: "View More",
    load_more: "Load More",
    title: "Title",
    default_title: "Enter a title here",
    category: "Category",
    select_category: "Select a category",
    description: "Description",
    default_description: "Write an awesome description",
    error_field: "Please fill in all required fields",
    content: "Content",
    create: "Create",
    update: "Update",
    delete: "Delete",
    success: "Success",
    error: "Error",
    msg_data_created: "The data has been created",
    msg_data_updated: "The data has been updated",
    msg_data_deleted: "The data has been deleted",
    msg_error_fetch: "Sorry, no obtain results on fetch",
    no_results: "No results found in last search",
    import: "Import Data",
    export: "Export Data",
    import_json: "Import Backup",
    pick_file: "Choose a File",
    pick_label: "Your Backup",
    error_import:
      "Some objects in the array do not contain the expected values.",
    success_import: "The import data has been successfully imported.",
    error_import_fetch: "An error occurred while importing your data.",
    search_by_title: "Search by Title/Category",
    empty_search_data: "Title or category is missing",
    empty_database: "The database is empty, please add new data",
    not_found: "404 Not Found",
    page_not_found:
      "The section you are trying to access does not exist. You may have entered the wrong address, or the section has been moved to a different URL. If you believe this is an error, please contact support.",
    back_to_home: "Back",
    language: "Language",
    are_you_sure: "Are you sure to delete?",
    access: "Access",
    share_link: "Share link",
    trash: "Trash",
    published: "Published",
    unpublished: "Unpublished",
    pin: "Pin",
    pinned: "Pinned",
    unpinned: "Unpinned",
    application: "Application",
    danger_zone: "Danger zone",
    change_state: "The state has been changed to",
  },
  es: {
    enter_the_code: "Por favor, escríba el código",
    about_title: "Acerca de D0C3+1",
    about_txt:
      "D0C3+1 es una herramienta simple pero efectiva para la creación rápida de fragmentos de código. Esta aplicación está diseñada pensando en programadores y desarrolladores que buscan una forma fácil y rápida de generar código útil para sus proyectos.",
    about_subtitle: "Bibliotecas Utilizadas",
    shared_links: "Enlaces Compartidos",
    home: "Inicio",
    add_new: "Agregar Nuevo",
    edit: "Editar",
    about_us: "Acerca de",
    search: "Buscar",
    cancel: "Cancelar",
    settings: "Configuración",
    view_more: "Ver Más",
    load_more: "Cargar Más",
    title: "Título",
    default_title: "Escribe algo aquí",
    category: "Categoría",
    select_category: "Selecciona una categoría",
    description: "Descripción",
    default_description: "Escribe una descripción asombrosa",
    error_field: "Por favor, completa los campos vacíos",
    content: "Contenido",
    create: "Crear",
    update: "Actualizar",
    delete: "Eliminar",
    success: "Éxito",
    error: "Error",
    msg_data_created: "Los datos han sido creados",
    msg_data_updated: "Los datos han sido actualizados",
    msg_data_deleted: "Los datos han sido eliminados",
    msg_error_fetch: "Lo sentimos, no se han obtenido resultados en la búsqueda",
    no_results: "Sin resultados para la búsqueda",
    import: "Importar datos",
    export: "Exportar datos",
    import_json: "Importar Respaldo",
    pick_file: "Seleccionar archivo",
    pick_label: "Tu Respaldo",
    error_import:
      "Algunos objetos en el arreglo no contienen los valores esperados.",
    success_import: "Los datos de importación han sido importados.",
    error_import_fetch: "Ocurrió un error al importar tus datos.",
    search_by_title: "Buscar por título/categoría",
    empty_search_data: "Falta título o categoría",
    empty_database:
      "La base de datos está vacía, por favor agrega nuevos datos",
    not_found: "404 no encontrado",
    page_not_found:
      "La sección que intentas abrir no existe. Es posible que hayas escrito incorrectamente la dirección o que la sección se haya movido a otra URL. Si crees que esto es un error, ponte en contacto con soporte.",
    back_to_home: "Volver",
    language: "Lenguaje",
    are_you_sure: "¿Esta seguro de borrarlo?",
    access: "Acceso",
    share_link: "Compartir enlace",
    trash: "Papelera",
    published: "Publicado",
    unpublished: "No publicado",
    pin: "Fijar",
    pinned: "Fijado",
    unpinned: "Desfijado",
    application: "Aplicación",
    danger_zone: "Zona de peligro",
    change_state: "Se ha cambiado el estado a",
  },
  gl: {
    enter_the_code: "Por favor escriba o código.",
    about_title: "Acerca de D0C3+1",
    about_txt:
      "D0C3+1 é unha ferramenta sinxela pero eficaz para a creación rápida de fragmentos de código. Esta aplicación está deseñada pensando en programadores e desenvolvedores que buscan unha forma fácil e rápida de xerar código útil para os seus proxectos.",
    about_subtitle: "Bibliotecas Utilizadas",
    shared_links: "Vínculos Compartidos",
    home: "Inicio",
    add_new: "Engadir Novo",
    edit: "Editar",
    about_us: "Sobre a App",
    search: "Buscar",
    cancel: "Cancelar",
    settings: "Axustes",
    view_more: "Ver Máis",
    load_more: "Cargar Máis",
    title: "Título",
    default_title: "Introduce un título aquí",
    category: "Categoría",
    select_category: "Selecciona unha categoría",
    description: "Descrición",
    default_description: "Escribe unha descrición impresionante",
    error_field: "Por favor, completa todos os campos obrigatorios",
    content: "Contido",
    create: "Crear",
    update: "Actualizar",
    delete: "Eliminar",
    success: "Éxito",
    error: "Error",
    msg_data_created: "Os datos foron creados",
    msg_data_updated: "Os datos foron actualizados",
    msg_data_deleted: "Os datos foron eliminados",
    msg_error_fetch: "O sentimos, non hemos obtenido resultados al obtener los datos.",
    no_results: "Non se atoparon resultados na última busca",
    import: "Importar Datos",
    export: "Exportar Datos",
    import_json: "Importar Copia de Seguridade",
    pick_file: "Escoller un Ficheiro",
    pick_label: "A súa Copia de Seguridade",
    error_import:
      "Algúns obxectos no conxunto non conteñen os valores esperados.",
    success_import: "Os datos de importación foron importados con éxito.",
    error_import_fetch: "Ocorreu un erro durante a importación dos seus datos.",
    search_by_title: "Buscar por Título/Categoría",
    empty_search_data: "Falta o título ou a categoría",
    empty_database: "A base de datos está baleira, engada novos datos",
    not_found: "404 Non Encontrado",
    page_not_found:
      "A sección que está a intentar acceder non existe. Pode que teña introducido a dirección incorrecta ou que a sección se trasladara a unha URL diferente. Se cre que isto é un erro, póñase en contacto co soporte.",
    back_to_home: "Volver",
    language: "Idioma",
    are_you_sure: "¿Está seguro de borralo?",
    access: "Acceso",
    share_link: "Compartir enlace",
    trash: "Papelera",
    published: "Publicado",
    unpublished: "Non publicado",
    pin: "Fixar",
    pinned: "Fixado",
    unpinned: "Non fixado",
    application: "Aplicación",
    danger_zone: "Zona de perigo",
    change_state: "Cambiouse o estado a",
  },
  de: {
    enter_the_code: "Bitte Code eingeben.",
    about_title: "Über D0C3+1",
    about_txt:
      "D0C3+1 ist ein einfaches, aber effektives Tool zur schnellen Erstellung von Code-Snippets. Diese Anwendung wurde für Programmierer und Entwickler entwickelt, die nach einer einfachen und schnellen Möglichkeit suchen, nützlichen Code für ihre Projekte zu generieren.",
    about_subtitle: "Verwendete Bibliotheken",
    shared_links: "Geteilte Links",
    home: "Startseite",
    add_new: "Neu Hinzufügen",
    edit: "Bearbeiten",
    about_us: "über app",
    search: "Suchen",
    cancel: "Abbrechen",
    settings: "Einstellungen",
    view_more: "Mehr Anzeigen",
    load_more: "Mehr Laden",
    title: "Titel",
    default_title: "Geben Sie hier einen Titel ein",
    category: "Kategorie",
    select_category: "Wählen Sie eine Kategorie",
    description: "Beschreibung",
    default_description: "Schreiben Sie eine großartige Beschreibung",
    error_field: "Bitte füllen Sie alle Pflichtfelder aus",
    content: "Inhalt",
    create: "Erstellen",
    update: "Aktualisieren",
    delete: "Löschen",
    success: "Erfolg",
    error: "Fehler",
    msg_data_created: "Die Daten wurden erstellt",
    msg_data_updated: "Die Daten wurden aktualisiert",
    msg_data_deleted: "Die Daten wurden gelöscht",
    msg_error_fetch: "Es wurden leider keine Ergebnisse für Ihre Suche gefunden.",
    no_results: "Keine Ergebnisse bei der letzten Suche",
    import: "Daten Importieren",
    export: "Daten Exportieren",
    import_json: "Backup Importieren",
    pick_file: "Datei Auswählen",
    pick_label: "Ihr Backup",
    error_import: "Einige Objekte im Array enthalten nicht erwartete Werte.",
    success_import: "Die Importdaten wurden erfolgreich importiert.",
    error_import_fetch:
      "Es ist ein Fehler beim Importieren Ihrer Daten aufgetreten.",
    search_by_title: "Nach Titel/Kategorie suchen",
    empty_search_data: "Titel oder Kategorie fehlt",
    empty_database: "Die Datenbank ist leer, bitte fügen Sie neue Daten hinzu",
    not_found: "404 Nicht Gefunden",
    page_not_found:
      "Der Abschnitt, den Sie zu öffnen versuchen, existiert nicht. Möglicherweise haben Sie die falsche Adresse eingegeben, oder der Abschnitt wurde an eine andere URL verschoben. Wenn Sie glauben, dass dies ein Fehler ist, kontaktieren Sie bitte den Support.",
    back_to_home: "Zurück",
    language: "Sprache",
    are_you_sure: "Sind Sie sicher, es zu löschen?",
    access: "Zugriff",
    share_link: "Link teilen",
    trash: "Papierkorb",
    published: "Veröffentlicht",
    unpublished: "Nicht veröffentlicht",
    pin: "Anheften",
    pinned: "Angeheftet",
    unpinned: "Nicht angeheftet",
    application: "Anwendung",
    danger_zone: "Gefahrenzone",
    change_state: "Der Status wurde geändert auf",
  },
};
